# Generated by Django 3.2.18 on 2023-04-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('create_time', models.TimeField(auto_now=True)),
                ('updated_time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
